#!/bin/bash
#SBATCH -A snic2017-7-315
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 05:00:00
#SBATCH -J bwa_index
#SBATCH --mail-type=ALL
#SBATCH --mail-user nikiforos.pyrounakis.0585@student.uu.se

#Modules
module load bioinfo-tools
module load bwa/0.7.8

#Your commands
bwa index hs38DH_new.fa
