#!/bin/bash
#SBATCH -A snic2017-7-315
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 10:00:00
#SBATCH -J vg_index
#SBATCH --mail-type=ALL
#SBATCH --mail-user nikiforos.pyrounakis.0585@student.uu.se

#Modules

#Your commands
singularity exec /home/georg/vg.sif vg index -x GRCh38_reference_index.xg GRCh38_reference_grap.vg
