#!/bin/bash
#SBATCH -A snic2017-7-315
#SBATCH -p core
#SBATCH -n 20
#SBATCH -t 120:00:00
#SBATCH -J vg_index_gcsa
#SBATCH --mail-type=ALL
#SBATCH --mail-user nikiforos.pyrounakis.0585@student.uu.se

#Modules

#Your commands
singularity exec /home/georg/vg.sif vg index -g GRCh38_reference_index.gcsa GRCh38_reference_grap.vg

