#!/bin/bash
#SBATCH -A snic2017-7-315
#SBATCH -p core
#SBATCH -n 10
#SBATCH -t 24:00:00
#SBATCH -J vg_map
#SBATCH --mail-type=ALL
#SBATCH --mail-user nikiforos.pyrounakis.0585@student.uu.se

#Modules

#Your commands
singularity exec /home/georg/vg.sif vg map -x GRCh38_reference_index.xg -f /proj/uppstore2017220/applied_bioinformatics/1_data/adams_data/NA10860_nano_R1.fastq.gz -f /proj/uppstore2017220/applied_bioinforminformatics/1_data/adams_data/NA10860_nano_R2.fastq.gz > GRCh38_mapped.gam
